name: Compressed Size

on: [pull_request]

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install latest NPM version
      run: npm install -g npm@latest

    - uses: preactjs/compressed-size-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        pattern: "{build/**/*.js,build/**/*.css}"
